geyser: add `transactions_status` filter
rpcpool/yellowstone-grpc pull request #310
Opened 2024-03-30 23:28 UTC by fanatid

@vovkman @NicolasPennie @godmodegalactus @grooviegermanikus what do you think about a new message for Atlas / Lite RPC? We do not need to receive all transaction details to know that transaction confirmed or not.

```proto
message SubscribeUpdateTransactionStatus {
  uint64 slot = 1;
  bytes signature = 2;
  bool is_vote = 3;
  uint64 index = 4;
  solana.storage.ConfirmedBlock.TransactionError err = 5;
}
```

2024-03-31 00:55 UTC, vovkman commented
We sub to all blocks so we wouldn't use this in atlas, but I could see this being useful for lots of other cases!

2024-04-02 14:48 UTC, godmodegalactus requested changes

2024-04-02 14:48 UTC, godmodegalactus commented on examples/rust/src/bin/client.rs
> +    transactions_status_signature: Option<String>,
Should be more like a vector of string, so that filtering can be done on multiple signatures in one subscription..

2024-04-02 19:41 UTC, fanatid commented on examples/rust/src/bin/client.rs
> +    transactions_status_signature: Option<String>,
good point but unfortunately in transactions filter we have signature as `optional string` not as `repeated string` :confused:

2024-04-03 00:46 UTC, merged